### ISSUE TITLE
Other useful commands that could be added

### ISSUE THREAD

**Issue by barberagianluca** [zxgio/r2-cheatsheet#1]
In configurations
Enabling/Disabling function demangling
e bin.demangle = true/false
e asm.demangle = true/false
- - - -
In section Printing: p
pdc     pseudo disassembler output in C-like syntax
~.tex code
`\texttt{pdc} [\texttt{@} \textit{fn-name}$|$\textit{addx}] & pseudo-disassemble function \textit{fn-name}/at address \textit{addx} , output in C-like syntax`
- - - -
get the call graph
agC -> in digraph code
agCj -> in json where 'imports' are the calls
- - - -
Force the execution of a command in the shell with two exclamation signs !!
"If a command starts with ! , the rest of the string is passed to currently loaded IO plugin (a debugger, for example). If no plugin can handle the command, posix_system() is called to pass the command to your shell. To make sure your command is directly passed to the shell, prefix it with two exclamation signs !! "
Example -> !!man ls

**Comment by zxgio** [comment]
Many thanks, I've included your suggestions (except for: 'agCj', because I don't want to duplicate all the commands that can also output in JSON format; the general idea of the 'j' suffix is already mentioned elsewhere)
